spring:
  application:
    name: mmc-sis
  profiles:
    active: dev
  jpa:
    open-in-view: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration-minutes: 60

management:
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: "0.1.0"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json
  info:
    title: "MMC SIS API"
    version: "0.1.0"